### ISSUE TITLE
progress problem thaumcraft stabilizer

### ISSUE THREAD

**Issue by ferrium42** [AllTheMods/ATM3-Expert#201]
i´m in the progress to get the blood altar, my first attempt ended in a mess with candles and skull, so i get the research for stabilizer - research and find out that i can´t craft them because they needed terrasteel and this need slate from a bloodaltar ... so i stuck or can try it with multiple items 

## Expected Behavior
What can i do? Someone have to help me , thaumcraft is not my favorite mod. 

## Current Behavior
Blood altar crafting is a mess without stabilizer

## Possible Solution
Or lower the recipe for stabilizer

## Steps to Reproduce

1.
2.
3.
4.

**Comment by bomber12309** [comment]
You don't need the stabilizers, you can just use stabilizer blocks (ex. skulls, candles, floating botania flowers, glimmering botania flowers, botania pylons)
They have to be symmetrical, and a type of block has diminishing returns (so for example 16 white candles would be less efficient than 16 candles of 4 different colors).
2 candles of each color will get you most of the stability you need, you can top it off with skulls and floating/glimmering botania flowers.

Hope this helps :)

(also, since this is more of a question than an issue, you can ask in the atm discord next time- you'll get an answer much quicker and it's easier to respond if you have follow-up questions)

**Comment by TheGoldCrayon** [comment]
^Bomber is correct. You don't *need* the stabilizer blocks that use power for infusion, they just help. You're able to do any infusion without them. Closing as this isn't an issue.
