### ISSUE TITLE
Three minor "Bugs?"

### ISSUE THREAD

**Issue by Zendien** [AllTheMods/ATM3-Expert#237]
1. When using the IF Mob Slaughter Factory to kill mobs, they still drop the Baubley Hearts Canister red hearts.

2. After using the tier 3 blood orb to Blood Transmute glowstone into luminessence, the hunger 3 effect and slowness 2 effect linger at 0.00 until you relog.

3. The tier 4 quest "It's so slippery" asks for steel blocks, steel scaffoldings and steel scaffolding slabs, that aren't the default outputs when actually crafting the items. (The IE book uses the same, so maybe this one belongs over at Immersive Petroleum)

All 3 bugs are reproducable since it happens every time

Version: ATM3e v1.6.1
Launcher: MultiMC

**Comment by rlnt** [comment]
Thanks for submitting an issue and reporting these to us!
Let me give some comment on each of them:

1. That is an external issue with Industrial Foregoing. That is nothing pack specific. They always drop with the Mob Slaughter Factory and there is nothing we can do about it. I don't think it's that bad tho.
2. That's also an external issue caused by the mod itself. I guess it would be the best to message the author. Since this mod was specifically made for All the Mods 3 Expert, I am sure I can contact the author directly to fix it.
3. I think the Immersive Petroleum entries use the ore dictionary in the Engineer's Manual to see if you have the right materials. I will need to adjust the quest to count the right blocks. Thanks for that.

**Comment by rlnt** [comment]
I closed this issue since I fixed the only problem that was fixable. Normally you have to split each issue into individual issue submissions.
To your reports:
1. As mentioned before, this is an external issue by Industrial Foregoing. We can't do anything about it.
2. I updated the pack a lot and I am no longer able to reproduce this bug so it should be gone. Tested it in Singleplayer and Multiplayer with each blood orb and dozens of glowstone.
3. This is fixed now. The quest should now properly track the right amounts and the right blocks which you get from crafting. The steel block was also giving some issues because it was converted to Mekanism steel blocks. This has also been fixed.

Thanks again for your contribution!
