### ISSUE TITLE
IE Crusher slows down on some recipes

### ISSUE THREAD

**Issue by Zendien** [AllTheMods/ATM3-Expert#238]
When trying to process iron ingots>pulverized iron and coal>pulverized coal, then Immersive Engineering Crusher slows down to a crawl. It eventually finishes, but incredibly slowly

**To Reproduce**
Throw, pipe, hopper an iron ingot into the Crusher and it will happen. Does it every time

Version: Atm3e 1.6.1
Launcher: MultiMC

**Comment by rlnt** [comment]
Thanks for bringing this up.
This issue is related to a known problem where ores in the crusher would crash your instance and then server (if on multiplayer). We haven't been able to figure out what's causing that and an issue report has already been made to Immersive Engineering.

We can just hope the author is able to see what's wrong and release a patch.
The issue is here: BluSunrize/ImmersiveEngineering#3854

**Comment by rlnt** [comment]
This issue was temporarily fixed in the referenced commit. After a lot of trying it seems like Netherending Ores is causing this behavior.
The author of the mod already implemented a fix but until the hotfix is pushed to a public jar, we will use the temporary fix.

This references the following issues:
BluSunrize/ImmersiveEngineering#3417
BluSunrize/ImmersiveEngineering#3826
BluSunrize/ImmersiveEngineering#3854
ICannt/Netherending-Ores#24

The commit this was fixed in is the following:
https://github.com/ICannt/Netherending-Ores/commit/91c1244459b33522784296bf22aaa26cea00b49a
