### ISSUE TITLE
A lot of Astral sorcery recipe's are so cheap compared to their combinationcrafting counterpart, Intentional?

### ISSUE THREAD

**Issue by daddy77gaming** [AllTheMods/ATM3-Expert#245]
Pay the extreme extra price to be able to automate, Is this intentional? Or Was/Is it intentional to remove basic astral sorcery recipes?

![image](https://user-images.githubusercontent.com/31905330/83616153-c6a39a00-a587-11ea-9bbe-7c4032c0a969.png)

![image](https://user-images.githubusercontent.com/31905330/83616078-aecc1600-a587-11ea-8c0a-2eadb47fb2d1.png)

![image](https://user-images.githubusercontent.com/31905330/83616410-17b38e00-a588-11ea-812a-abf13b16a4c6.png)

![image](https://user-images.githubusercontent.com/31905330/83616436-213cf600-a588-11ea-8535-fedefa951510.png)

**Versions (please complete the following information):**
 - Modpack version: All the Mods 3 Expert - Shedding Tiers - v1.6.1
 - used Launcher:  MultiMC

**Comment by rlnt** [comment]
That is indeed intentional.
I was talking to some people who played through the pack completely and they were annoyed that some recipes weren't able to be automated due to Astral Sorcery's crafting behaviour.

I made these new recipes so you are able to automate them in the late game but at a high cost. But if you are that late in the pack, you should have everything automated that is needed for those recipes. Especially with the possibility of mining lasers, void ore miners and most important: AgriCraft.
