### ISSUE TITLE
What should be in dungeon loot?

### ISSUE THREAD

**Issue by oly2o6** [AllTheMods/ATM3-Expert#45]
This if for everyone to contribute to, what should be in loot chests that doesn’t break progression, such as building wands and other things you can think of

**Comment by bomber12309** [comment]
-very rare excavate modifiers
-reinforcement modifiers, mending/moss, silky jewels, width++ and height++ modifiers
-gendustry parts - may incite people to use bees, the recipes aren't gated too much (farthest gate is the diamonds), doesn't cheat progress because you need to be far enough to make the other parts (genetics labware (basically allows gendustry machines to work) requires diamonds)
-random bee samples!
-formation and conversion wands from Astral Sorcery (building/swapping wands, basically)
-gadgets from Building Gadgets
-black/er lotuses
-spectre coils (transferring, not generating) (useless without a spectre energy injector, but pretty useful once you get there)
-compacting drawers, drawer controllers, drawer upgrades
-forestry bags, thermal satchels
-thermal's upgrade/conversion kits, random augments
-ic2c RE-batteries, regular circuits
-rubber, silverwood and greatwood saplings
-actually additions' rings
-conduits ? not sure if they're intentionally gated or if it's just because the alloys are gated
-thermal's ducts, servos

just my thoughts, obviously my thoughts may be bad :)
