### ISSUE TITLE
Kiln Doesnt work Properly!

### ISSUE THREAD

**Issue by drizzs** [AllTheMods/ATM3-Expert#7]
Kiln doesnt make unfired barrels into white porcelain barrels and also doesnt cook unfired porcelain faucets.

## Expected Behavior
Should cook those items for us before we get a furnace

## Current Behavior
gotta cheat or use a furnace

## Possible Solution
Add those items to the mods override <3

**Comment by oly2o6** [comment]
Fixed in next version

**Comment by Blatts12** [comment]
https://imgur.com/a/Nu6f8Z6

I downloaded pack and there is no recipe

**Comment by TheGoldCrayon** [comment]
We were just made aware shortly before you posted this. We are working on fixing this. Thank you for your patience.

Also, it would help if you made a new issue rather than posting on a closed one. This is on the *last* page of closed issues, and since it is closed, we aren't looking here anymore. In general, commenting on closed issues isn't a good idea as it rarely will get looked at.

**Comment by Boomflex** [comment]
>In general, commenting on closed issues isn't a good idea as it rarely will get looked at.

To be fair, closing an Issue as "Fixed in next version" 6 months ago is probably not a good idea, especially when it wasn't...

**Comment by TheGoldCrayon** [comment]
When this was closed, it was fixed. There was a mistake in the recent update that caused this issue to reappear. Please don't assume that the issue was never solved.

**Comment by oly2o6** [comment]
Due to a bug in Atum when adding a new crafttweaker recipe to the kiln it will remove some of the others randomly, going to speak to the author but for now go to a village and get a furnace through world gen
